#include <stdio.h>
 
 void hailstone(int n)
    {
    int count=0;//用来记录下标
    printf("Hailstone generated by %d:\n",n);
    while(n!=1)
    { 
      printf("%4d",n);//使用四个字节标准化输出，可以保证右对齐
     if(n%2==0){
        n/=2;
     }else{
        n=3*n+1;
     } //冰雹序列的生成规则
     count++;
     if (count % 6 == 0) {
            printf("\n");
    }//如果是第七个，那么先换行，再输出
    }
    printf("%4d\n",n);
    count++;
    printf("Number of hailstone generated: %d",count);//打印出hailstone序列数的个数
 }
 int main(void)
 {
     int n;
     scanf("%d", &n);
     hailstone(n);
     return 0;
 }